### ISSUE TITLE
Compiled Plugin?

### ISSUE THREAD

**Issue by jpickerell** [djhaskin987/groupme-purple#1]
@djhaskin987 
First, very much appreciate you forking this from @alyssarosenzweig project and getting it to work!!! I still had the OLD Google Code version from Ken Patel. I hadn't loaded Pidgin for a few years and in doing so last week, discovered the old plugin I had wouldn't let me log into my GroupMe account.

Any way I might be able to get you to post compiled versions of this as a release? I've never complied anything in my life, so not sure where to even start in trying to compile this plugin for Windows? And maybe we can get the Pidgin crew to link to your updated version from their plugin page?

Thanks!
Jared P.

**Comment by djha-skin** [comment]
Hey Jared.

Um, I think I'd be able to post compilation instructions for Linux, and I know you can compile it for Windows because there's code that allows you to do so in the repository, but I never got that to work myself. I wasn't that motivated to do so because there's actually a pretty nice GroupMe app on Windows in the store. There's nothing like that on Linux and so I got this to work instead.

Posting precompiled binaries for Linux is harder than it sounds because the compiled binaries don't statically compile by default they dynamically compile. That basically means I'd have to compile it for every different version of Linux that I'd want to support, so I would at least probably be doing it for Rocky Linux 9, Rocky Linux 8, and the most recent LTS version of Ubuntu, but then you couldn't install it on anything but those particular platforms. So I don't know how useful that would be to you.

I can get you some compilation instructions on Linux though. I could even write a script and let you run that, that's not too difficult. Compiling on Linux is super easy because people have to do it so often that Linux makes it easy to do, very scriptable.

I'll see if I can spend some time with it this weekend and see if I can't get it to compile on Windows, I'll let you know. But I got to say I've already tried and it's not the easiest thing in the world. You have to have gtk and pidgin checked out on your machine. Good news is, if I can get it to work, posting a precompiled binary should work for you because all I have to do is post one instead of like 15.

**Comment by djha-skin** [comment]
Hey @jpickerell , just compiled a windows plugin. Should be on the releases page, or this link: https://github.com/djhaskin987/groupme-purple/releases/download/0.87.0/libgroupme.dll

**Comment by djha-skin** [comment]
The previous work done above is only for the 64 bit version of pidgin, which is mostly useless to people. However, I was finally able a few weekends ago to compile the 32-bit version (which should work with your copy of pidgin). I'll get it up today hopefully :)

**Comment by djha-skin** [comment]
There is now a compiled plugin for windows: https://github.com/djhaskin987/groupme-purple/releases/tag/0.88.0
